### ISSUE TITLE
License

### ISSUE THREAD

**Issue by robcresswell** [joyent/node-docker-file-parser#7]
Hi!

I had a question regarding the license choice; is there any reason it wasn't something more permissive such as MIT? Not a criticism or request for change, just a curiosity, as it blocked us from using the project and meant we ended up writing own own parser.

**Comment by twhiteman** [comment]
Sure - MPL is the license chosen by Joyent itself. You can read more on the license choice here:
https://www.joyent.com/blog/sdc-and-manta-are-now-open-source

**Comment by robcresswell** [comment]
Cool, thanks @twhiteman
