### ISSUE TITLE
Parsing commands with question mark fails

### ISSUE THREAD

**Issue by jstastny** [joyent/node-docker-file-parser#9]
I found a bug parsing Dockerfile that has `?` in the `RUN` command.

Minimal example is:
```Dockerfile
FROM cirrusci/wget

RUN wget http://google.com?hello=world
```

The expectation is that this would produce 2 commands after parse, but it actually produces 3:
```javascript
[
  {
    name: 'FROM',
    lineno: 1,
    args: 'cirrusci/wget',
    raw: 'FROM cirrusci/wget'
  },
  {
    name: 'RUN',
    lineno: 3,
    args: 'wget http://google.com',
    raw: 'RUN wget http://google.com'
  },
  { name: 'HELLO=WORLD', lineno: 4, args: '', raw: 'hello=world' }
]
```

I have created a (failing) test to show this: https://github.com/joyent/node-docker-file-parser/commit/f0da8b75d0dc46492a1e2f616ce58c8ef02690e0

**Comment by twhiteman** [comment]
Good catch, and thanks for the detailed report with the test case. I'll take a look into this issue.

**Comment by jstastny** [comment]
Thanks a lot for a quick fix!
